### ISSUE TITLE
Malformed payload

### ISSUE THREAD

**Issue by rostyslav-andrushko** [meritoo/limesurvey-api-client#1]
I have this error: 
Oops, an error occurred while running method. Is there everything ok? Details:
- error: Malformed payload,
- method: get_session_key,
- arguments: (no arguments).
Who knows what it is??

**Comment by meritoo** [comment]
@rostandr Sounds like a problem with data that is prepared to send to LimeSurvey instance. First tip, right now, is to enable the `debug` mode: https://github.com/meritoo/limesurvey-api-client#debug-mode and verify your log. You have to look for data generated by this line: https://github.com/fguillot/JsonRPC/blob/ea2720b13e986bbf23e832b135c84c91ead7259f/src/JsonRPC/HttpClient.php#L282.

Maybe it will be helpful: the `$payload` variable is not an array and that's why you've got an exception (https://github.com/fguillot/JsonRPC/blob/ea2720b13e986bbf23e832b135c84c91ead7259f/src/JsonRPC/Validator/JsonFormatValidator.php#L26).

**Comment by rostyslav-andrushko** [comment]
I solved my problem, in limesurvey json-rpc was disabled and I did not know it. Issue can be closed

**Comment by meritoo** [comment]
@rostandr Great. Thanks for information.
